base_image_registry: ghcr.io/ublue-os
description: A starting point for further customization of uBlue images. Make your own! https://ublue.it/making-your-own/
scripts:
  pre:
    # Automatically runs script files within "scripts/pre/".
    - autorun.sh
  post:
    # Automatically runs script files within "scripts/post/".
    - autorun.sh
    - dconf-update.sh
rpm:
  repos:
  # Tip: Use `%FEDORA_VERSION%` instead of static Fedora version numbers,
  # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%FEDORA_VERSION%/atim-starship-fedora-%FEDORA_VERSION%.repo
  # A list of .repo files that aren't in the COPR, added by scripts/pre/proprietaryrepos.sh
  repo-files:
    - https://raw.githubusercontent.com/scottames/ublue/live/repos/1password.repo
    - https://repo.vivaldi.com/stable/vivaldi-fedora.repo
  install:
    - 1password
    - 1password-cli
    - fish
    - google-droid-sans-fonts
    - google-noto-fonts-common
    - google-roboto-fonts
    - langpacks-en
    # GNOME's GTK4 theme, Libadwaita. Already included in Silverblue, but not
    # other spins. You can remove if you aren't using yafti, but many native
    # apps and binaries require it, so it's a good idea to always include it
    # if you ever download or compile any custom software on your machine.
    - libadwaita
    # https://github.com/oae/gnome-shell-pano
    - libgda
    - libgda-sqlite
    - lm_sensors # required by freon gnome-ext
    - mozilla-fira-fonts-common
    - mscore-fonts-all
    - netcat
    - pulseaudio-utils
    - python3-pip # needed by Yafti
    - yubico-piv-tool-devel
    - yubikey-manager
    - yubikey-manager-qt
    - vivaldi-stable
    - wl-clipboard
    - xclip
  # Fixes packages that install to /opt by symlinking:
  #   ../../usr/lib/opt/[name here]
  #   in /opt/[name here]
  optpackages:
    - 1Password
    - vivaldi
  remove:
    # Remove the native firefox (from Fedora) in favor of the Flatpak.
    # - firefox
    # - firefox-langpacks
    - opensc
firstboot:
  yafti: false
  flatpaks:
    - com.github.marhkb.Pods
    - com.google.Chrome
    - com.raggesilver.BlackBox
    - io.github.celluloid_player.Celluloid
    - io.wavebox.Wavebox
    - md.obsidian.Obsidian
    - org.flameshot.Flameshot
    - org.gimp.GIMP
    - org.kde.krita
    - org.wezfurlong.wezterm
    - us.zoom.Zoom
