- type: fonts
  fonts:
    nerd-fonts:
      - FiraCode
      - Hack
      - SourceCodePro
      - Terminus
      - JetBrainsMono
      - NerdFontsSymbolsOnly
    google-fonts:
      - Roboto
      - Open Sans
