---
type: rpm-ostree
repos:
  - https://raw.githubusercontent.com/scottames/ublue/live/config/repos/1password.repo
  - https://raw.githubusercontent.com/scottames/ublue/live/config/repos/tailscale.repo
  - https://repo.vivaldi.com/stable/vivaldi-fedora.repo
  - https://repository.mullvad.net/rpm/stable/mullvad.repo
install:
  - 1password
  - 1password-cli
  - arm-image-installer
  - firewall-config
  - fish
  - google-droid-sans-fonts
  - google-noto-color-emoji-fonts
  - google-noto-emoji-fonts
  - google-noto-fonts-common
  - google-roboto-fonts
  - langpacks-en
  - lm_sensors  # required by freon gnome-ext
  - mozilla-fira-fonts-common
  - mscore-fonts-all
  - mullvad-vpn
  - netcat
  - pam-u2f
  - pamu2fcfg
  - pipx
  - pulseaudio-utils
  - python3-pip  # needed by Yafti
  - tailscale
  # - vivaldi-stable
  - wl-clipboard
  - xclip
  - yubico-piv-tool-devel
  - yubikey-manager
  - yubikey-manager-qt
  #Virt-manager packages from bluefin-dx
  - edk2-ovmf
  - genisoimage
  - libvirt
  - qemu
  - qemu-char-spice
  - qemu-device-display-virtio-gpu
  - qemu-device-display-virtio-vga
  - qemu-device-usb-redirect
  - qemu-img
  - qemu-system-x86-core
  - qemu-user-binfmt
  - virt-manager
  # GNOME's GTK4 theme, Libadwaita. Already included in Silverblue, but not
  # other spins. You can remove if you aren't using yafti, but many native
  # apps and binaries require it, so it's a good idea to always include it
  # if you ever download or compile any custom software on your machine.
  - libadwaita
  # zsa voyager
  - gtk3
  - libusb
  - webkit2gtk3
  - webkit2gtk4.0
  # https://github.com/oae/gnome-shell-pano
  - libgda
  - libgda-sqlite
optfix:
  - 1Password
  - vivaldi
remove:
  # Remove the native firefox (from Fedora) in favor of the Flatpak.
  # - firefox-langpacks
  # - firefox
  - opensc
