# image will be published to ghcr.io/<user>/<name>
name: ublue-nvidia
# description will be included in the image's metadata
description: scottames' custom Fedora Silverblue native container image powered by Universal Blue.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: common-packages.yml
  - from-file: common-scripts-post-packages.yml
  - from-file: common-fonts.yml
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - ublue-update # https://github.com/ublue-os/ublue-update
      - dconf-update-service # a service unit that updates the dconf db on boot
  - from-file: common-yafti.yml
