name: build-ublue
on:
  schedule:
    - cron: "20 22 * * *"
  push:
    branches:
      - live
      - template
      - main
    paths-ignore:
      - "**.md"
      - "**.txt"
  pull_request:
  workflow_dispatch:
env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_REGISTRY_OWNER: ${{ github.repository_owner }}
jobs:
  push-ghcr:
    name: Build & Push
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        image_variant: [silverblue]
        image_flavor: [main, nvidia]
        base_name: [ublue]
        major_version: [38]
        recipe:
          - recipe.yml
    steps:
      # Checkout push-to-registry action GitHub repository
      - name: Checkout Push to Registry action
        uses: actions/checkout@v3
      - name: Add yq for reading recipe.yml
        uses: mikefarah/yq@v4.34.2
      - name: Gather image data from recipe
        run: |
          if [[ "${{ matrix.image_flavor }}" == "main" ]]; then
              echo "IMAGE_NAME=${{ matrix.base_name }}" >> $GITHUB_ENV
          elif [[ "${{ matrix.image_variant }}" == "silverblue" ]]; then
              echo "IMAGE_NAME=${{ format('{0}-{1}', matrix.base_name, matrix.image_flavor) }}" >> $GITHUB_ENV
          elif [[ "${{ matrix.image_flavor }}" == "main" ]]; then
              echo "IMAGE_NAME=${{ format('{0}-{1}', matrix.base_name, matrix.image_variant) }}" >> $GITHUB_ENV
          else
              echo "IMAGE_NAME=${{ format('{0}-{1}-{2}', matrix.base_name, matrix.image_variant, matrix.image_flavor) }}" >> $GITHUB_ENV
          fi

          echo "BASE_IMAGE_REGISTRY=$(yq '.base_image_registry' ./${{ matrix.recipe }})" >> $GITHUB_ENV
          echo "RECIPE=${{ matrix.recipe }}" >> $GITHUB_ENV
          echo "IMAGE_DESCRIPTION=$(yq '.description' ./${{ matrix.recipe }})" >> $GITHUB_ENV
          echo "FEDORA_MAJOR_VERSION=${{ matrix.major_version }}" >> $GITHUB_ENV
      - name: Generate tags
        id: generate-tags
        shell: bash
        run: |
          # Generate a timestamp for creating an image version history
          TIMESTAMP="$(date +%Y%m%d)"
          MAJOR_VERSION="${{ env.FEDORA_MAJOR_VERSION }}"
          COMMIT_TAGS=()
          BUILD_TAGS=()
          # Have tags for tracking builds during pull request
          SHA_SHORT="${GITHUB_SHA::7}"
          COMMIT_TAGS+=("pr-${{ github.event.number }}-${MAJOR_VERSION}")
          COMMIT_TAGS+=("${SHA_SHORT}-${MAJOR_VERSION}")

          BUILD_TAGS=("${MAJOR_VERSION}" "${MAJOR_VERSION}-${TIMESTAMP}")

          BUILD_TAGS+=("${TIMESTAMP}")
          BUILD_TAGS+=("latest")

          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
              echo "Generated the following commit tags: "
              for TAG in "${COMMIT_TAGS[@]}"; do
                  echo "${TAG}"
              done
              alias_tags=("${COMMIT_TAGS[@]}")
          else
              alias_tags=("${BUILD_TAGS[@]}")
          fi
          echo "Generated the following build tags: "
          for TAG in "${BUILD_TAGS[@]}"; do
              echo "${TAG}"
          done
          echo "alias_tags=${alias_tags[*]}" >> $GITHUB_OUTPUT
      - name: Get current version
        id: labels
        run: |
          ver=$(skopeo inspect docker://${{ env.BASE_IMAGE_REGISTRY }}/${{ matrix.image_variant }}-${{ matrix.image_flavor }}:${{ matrix.major_version }} | jq -r '.Labels["org.opencontainers.image.version"]')
          echo "VERSION=$ver" >> $GITHUB_OUTPUT
      # Workaround bug where capital letters in your GitHub username make it impossible to push to GHCR.
      # https://github.com/macbre/push-to-ghcr/issues/12
      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ env.IMAGE_REGISTRY }}
      - name: Lowercase Image
        id: image_case
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ env.IMAGE_NAME }}
      - name: Image Metadata
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: |
            ${{ steps.image_case.outputs.lowercase }}
          labels: |
            org.opencontainers.image.title=${{ steps.image_case.outputs.lowercase }}
            org.opencontainers.image.version=${{ steps.labels.outputs.VERSION }}
            org.opencontainers.image.description=${{ env.IMAGE_DESCRIPTION }}
            io.artifacthub.package.readme-url=https://raw.githubusercontent.com/scottames/ublue/main/README.md
            io.artifacthub.package.logo-url=https://avatars.githubusercontent.com/u/120078124?s=200&v=4
      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Containerfile
          image: ${{ steps.image_case.outputs.lowercase }}
          tags: |
            ${{ steps.generate-tags.outputs.alias_tags }}
          build-args: |
            IMAGE_VARIANT=${{ matrix.image_variant }}
            IMAGE_FLAVOR=${{ matrix.image_flavor }}
            IMAGE_NAME=${{ steps.image_case.outputs.lowercase }}
            FEDORA_MAJOR_VERSION=${{ env.FEDORA_MAJOR_VERSION }}
            BASE_IMAGE_REGISTRY=${{ env.BASE_IMAGE_REGISTRY }}
            RECIPE=${{ matrix.recipe }}
            IMAGE_REGISTRY=${{ steps.registry_case.outputs.lowercase }}
            IMAGE_REGISTRY_OWNER=${{ env.IMAGE_REGISTRY_OWNER }}
          labels: ${{ steps.meta.outputs.labels }}
          oci: false
      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/live'
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ steps.registry_case.outputs.lowercase }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/live'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Sign container
      - uses: sigstore/cosign-installer@v3.1.1
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/live'
      - name: Sign container image
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/live'
        run: |
          cosign sign -y --key env://COSIGN_PRIVATE_KEY \
            ${{ steps.registry_case.outputs.lowercase }}/${{ steps.image_case.outputs.lowercase }}@${TAGS}
        env:
          TAGS: ${{ steps.push.outputs.digest }}
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
      - name: Echo outputs
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/live'
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"
